[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "godot-hpa"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "posix-ipc",
    "numpy",
]

[project.optional-dependencies]
gymnasium = ["gymnasium"]
dev = [
    "matplotlib",
    "pyqt5",
    "pandas"
]

[tool.hatch.build.targets.wheel]
packages = ["godot_hpa"]