[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "py-vga"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "posix-ipc",
    "numpy",
]

[project.optional-dependencies]
gymnasium = ["gymnasium"]
dev = [
    "py-vga[gymnasium]",
    "matplotlib",
    "pyqt5",
    "pandas",
    "opencv-python",
]
train = [
    "py-vga[gymnasium]",
    "torch",
    "tyro",
    "tensorboard",
]

[tool.hatch.build.targets.wheel]
packages = ["py_vga"]